[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "django"
version = "1.0.0"
description = "widget for Django admin"
authors = [
  { name = "sarath" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
